# Generated by Django 4.2.20 on 2025-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_lostitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
